#!/bin/bash
set -e
SRC=$1
DST=$2
TMP=`mktemp`
if [ -z "${SRC}" ]; then
    echo "No source specified"
    exit
fi
if [ -z "${DST}" ]; then
    DST="$PWD/"$(basename $SRC)
fi

if [ -d "$DST" ]; then
    DST="$DST/"$(basename $SRC)
fi

SRC_DIR=$(cd $(dirname "$DST"); pwd)
DST=$SRC_DIR/$(basename $DST)

rm -f $DST
tmux pipe-pane
tmux send Enter
tmux send 'split -u -b 100k --filter '"'"'gzip -c | base64 -w 0 | echo "~BEGIN~$(</dev/stdin)~END~"'"' $SRC ; echo "~FINISH~" ; echo"
tmux pipe-pane 'awk '"'"'{ if ($0 !~ /split /) {if ($0 ~ /~FINISH~/) {print $0 > "'"$TMP"'"; system("")}else {sub(/.*~BEGIN~/, ""); sub(/~END~.*/, ""); print} }}'"'"' | base64 -d | gunzip >>'"$DST"
tmux send Enter

while ! grep -q "~FINISH~" "$TMP"; do
    sleep 0.1
done
tmux pipe-pane

rm -f "$TMP"

